name: Release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get latest go version
        id: version
        run: |
          echo ::set-output name=go_version::$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g')
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.version.outputs.go_version }}
          
      - name: Build geosite
        id: build
        run: |
            git update-index --chmod=+x .github/release-rule-set.sh
          # go run -v .

      - name: Get geosite.dat geoip.dat files from Loyalsoldier
        run: |
          wget -O geosite.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
          wget -O geoip.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
          #wget https://github.com/Loyalsoldier/geoip/raw/release/geoip.dat
          
      - name: Build db file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
           go install -trimpath -ldflags="-s -w -buildid=" github.com/metacubex/geo/cmd/geo@master
           geo convert site -i v2ray -o sing -f geosite.db ./geosite.dat
           geo convert ip -i v2ray -o sing -f geoip.db ./geoip.dat
   
      - name: Release rule sets
        if: steps.build.outputs.skip != 'true'
        run: |
          chmod +x ../release-rule-set.sh
         # git update-index --chmod=+x ../release-rule-set.sh
         # chmod +x .github/release-rule-set.sh
          mkdir rule-set
          ../release-rule-set.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generate sha256 hash
        if: steps.build.outputs.skip != 'true'
        run: |
          sha256sum geosite.db > geosite.db.sha256sum
          
      - uses: dev-drprasad/delete-older-releases@v0.3.2
        if: steps.build.outputs.skip != 'true'
        with:
          keep_latest: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Release geosite
        if: steps.build.outputs.skip != 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.build.outputs.tag }}
          files: |
            geosite.db
            sha256sum
