name: Release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get latest go version
        id: version
        run: |
          echo ::set-output name=go_version::$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g')
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.version.outputs.go_version }}
          
      - name: Build geosite
        id: build
        run: |
           go run -v .
           
           

      - name: Get geosite.dat geoip.dat files from Loyalsoldier
        run: |
          wget -O geosite.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
          wget -O geoip.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
          # wget https://github.com/Loyalsoldier/geoip/raw/release/geoip.dat
          
      - name: Build  db file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
           go install -trimpath -ldflags="-s -w -buildid=" github.com/metacubex/geo/cmd/geo@master
           geo convert site -i v2ray -o sing -f geosite.db ./geosite.dat
           geo convert ip -i v2ray -o sing -f geoip.db ./geoip.dat



      - name: Move db and geosite srs files
        run: |
          mkdir -p ./publish/
          # wget https://raw.githubusercontent.com/xishang0128/geoip/release/Country.mmdb -O ./publish/country-lite.mmdb
          # wget https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb -O ./publish/country.mmdb
          install -Dp ./geoip.dat ./publish/
          install -Dp ./geosite.dat ./publish/
          install -Dp ./geoip.db ./publish/
          install -Dp ./geosite.db ./publish/
          
          install -Dp ./rule-set/geosite-china-list.srs ./publish/
          install -Dp ./rule-set/geosite-gfw.srs ./publish/
          install -Dp ./rule-set/geosite-geolocation-!cn.srs ./publish/
          install -Dp ./rule-set/geosite-category-ads-all.srs ./publish/
          install -Dp ./rule-set/geosite-google.srs ./publish/
          install -Dp ./rule-set/geosite-apple.srs ./publish/
          install -Dp ./rule-set/geosite-telegram.srs ./publish/
          install -Dp ./rule-set/geosite-steam.srs ./publish/
          install -Dp ./rule-set/geosite-youku.srs ./publish/
          install -Dp ./rule-set/geosite-cloudflare.srs ./publish/
          install -Dp ./rule-set/geosite-cloudflare-cn.srs ./publish/
          install -Dp ./rule-set/geosite-fastly.srs ./publish/
          install -Dp ./rule-set/geosite-twitter.srs ./publish/
          install -Dp ./rule-set/geosite-facebook.srs ./publish/
          install -Dp ./rule-set/geosite-facebook-dev.srs ./publish/
          install -Dp ./rule-set/geosite-win-spy.srs ./publish/
          install -Dp ./rule-set/geosite-win-extra.srs ./publish/
          install -Dp ./rule-set/geosite-win-update.srs ./publish/
          install -Dp ./rule-set/geosite-alibabacloud.srs ./publish/
          install -Dp ./rule-set/geosite-alibaba@!cn.srs ./publish/
          install -Dp ./rule-set/geosite-youtube.srs ./publish/
          install -Dp ./rule-set/geosite-youtube@cn.srs ./publish/
          install -Dp ./rule-set/geosite-okx@cn.srs ./publish/
          install -Dp ./rule-set/geosite-binance.srs ./publish/
          install -Dp ./rule-set/geosite-okx.srs ./publish/
          install -Dp ./rule-set/geosite-apple-dev.srs ./publish/
          install -Dp ./rule-set/geosite-tencent.srs ./publish/
          
          
          cd ./publish || exit 1
          sha256sum geoip.dat > geoip.dat.sha256sum
          sha256sum geosite.dat > geosite.dat.sha256sum
 
          sha256sum geoip.db > geoip.db.sha256sum          
          sha256sum geosite.db > geosite.db.sha256sum      
           
      - name: Release geosite rule sets
        if: steps.build.outputs.skip != 'true'
        run: |
          chmod +x .github/release-rule-set.sh
          cd rule-set
          set -e -o pipefail
          git init
          git config --local user.email "github-action@users.noreply.github.com"
          git config --local user.name "GitHub Action"
          git remote add origin https://github-action:$GITHUB_TOKEN@github.com/gtpass/dbrules.git
          git branch -M geosite-rule-set
          git add .
          git commit -m "Update rule-set"
          git push -f origin geosite-rule-set
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build geoip
        id: buildgeoip
        run: |
           rm -rf ./rule-set/
           cd .geoip  || exit 1
           go run -v .
           
      - name: Move  geoip srs files
        run: |
          #install -Dp ./rule-set/geoip-cn.srs ./publish/
          
      - name: Release geoip rule sets
        if: steps.build.outputs.skip != 'true'
        run: |
          chmod +x .github/release-rule-set.sh
          cd rule-set
          set -e -o pipefail
          git init
          git config --local user.email "github-action@users.noreply.github.com"
          git config --local user.name "GitHub Action"
          git remote add origin https://github-action:$GITHUB_TOKEN@github.com/gtpass/dbrules.git
          git branch -M geoip-rule-set
          git add .
          git commit -m "Update rule-set"
          git push -f origin geoip-rule-set
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generate sha256 hash
        if: steps.build.outputs.skip != 'true'
        run: |
          sha256sum geoip.dat > geoip.dat.sha256sum
          sha256sum geosite.dat > geosite.dat.sha256sum
 
          sha256sum geoip.db > geoip.db.sha256sum          
          sha256sum geosite.db > geosite.db.sha256sum   
          
      - uses: dev-drprasad/delete-older-releases@v0.3.2
        if: steps.build.outputs.skip != 'true'
        with:
          keep_latest: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create and Upload Release
        id: upload_release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: Release ${{ env.BUILDTIME }}
          tag: latest
          file_glob: true
          overwrite: true
          file: ./publish/*

      - name: Git push assets to "release" branch
        run: |
          cd publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "Released on ${{ env.BUILDTIME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release

      - name: Purge jsdelivr CDN
        run: |
          cd publish || exit 1
          for file in $(ls); do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@release/${file}"
          done
